from django.db import models


class Person(models.Model):
    name = models.CharField('Полное имя', max_length=50)


class Patients(models.Model):
    organization = models.TextField('Организация', null=False, blank=True)
    patientFIO = models.TextField('ФИО пациента', null=True)
    male = models.TextField('Пол пациента', null=True)
    age = models.TextField('Возраст пациента', null=True)
    length = models.TextField('Рост пациента', null=True)
    weigth = models.TextField('Вес пациента', null=True)
    pregantPeriod = models.TextField('Срок беременности', null=True)
    childStatus = models.TextField('Состояние плода', null=True)
    sopDiagnoses = models.TextField('Сопутствующие заболевания', null=True)
    bodyTemperature = models.TextField('Температура тела мин-макс за сутки (0С)', null=True)
    breethTemp = models.TextField('Частота дыхательных движений (Мин^-1)', null=True)
    heartRate = models.TextField('Частота сердечных сокращений (Мин^-1)', null=True)
    AD = models.TextField('АД (Мм.рт.ст.)', null=True)
    o2Level = models.TextField('Уровень насыщения крови кислором(SpO2 при возможности PaO2) (%)', null=True)
    dyspnea = models.TextField('Одышка', null=True)
    cough = models.TextField('Кашель', null=True)
    sputum = models.TextField('Мокрота', null=True)
    hemoglobin = models.TextField('Гемоглобин (г\л)', null=True)
    leukocytes = models.TextField('Лейкоциты (Клеток 10^9)', null=True)
    lymphocytes = models.TextField('Лимфоциты (%)', null=True)
    platelets = models.TextField('Тромбоциты (Клеток 10^9)', null=True)
    ESR = models.TextField('СОЭ (Мм/час)', null=True)
    cReactiveProtein = models.TextField('С-реактивный белок (г\л)', null=True)
    oxygenTension = models.TextField('Респираторный индекс', null=True)
    pH = models.TextField('pH', null=True)
    oxygenFraction = models.TextField('Фракция кислорода на вдохе (%)', null=True)
    respirationRate = models.TextField('Частота дыханий (Мин^-1)', null=True)
    respiratoryVolume = models.TextField('Дыхательный объем (мл)', null=True)
    endExpiratoryPressure = models.TextField('Конечно-экспираторное давление (См.вод.ст.)', null=True)
    ventilationMode = models.TextField('Режим ИВЛ', null=True)
    status = models.TextField('Оценка состояния', null=True)
    doctor = models.TextField('Врач', null=True)
    phone = models.TextField('Контактный телефон', null=True)
    eMail = models.TextField('e-mail', null=True)
    daysUndersupervision = models.TextField('Количество суток под наблюдением в ДРКЦ', null=True)
    enterDate = models.TextField('Дата поступления', null=True)
    entryDate = models.TextField('Дата внесения', null=True)