# Generated by Django 3.1.2 on 2020-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.TextField(blank=True, verbose_name='Организация')),
                ('patientFIO', models.TextField(verbose_name='ФИО пациента')),
                ('male', models.TextField(verbose_name='Пол пациента')),
                ('age', models.TextField(verbose_name='Возраст пациента')),
                ('length', models.TextField(verbose_name='Рост пациента')),
                ('weigth', models.TextField(verbose_name='Вес пациента')),
                ('pregantPeriod', models.TextField(verbose_name='Срок беременности')),
                ('childStatus', models.TextField(verbose_name='Состояние плода')),
                ('sopDiagnoses', models.TextField(verbose_name='Сопутствующие заболевания')),
                ('bodyTemperature', models.TextField(verbose_name='Температура тела мин-макс за сутки (0С)')),
                ('breethTemp', models.TextField(verbose_name='Частота дыхательных движений (Мин^-1)')),
                ('heartRate', models.TextField(verbose_name='Частота сердечных сокращений (Мин^-1)')),
                ('AD', models.TextField(verbose_name='АД (Мм.рт.ст.)')),
                ('o2Level', models.TextField(verbose_name='Уровень насыщения крови кислором(SpO2 при возможности PaO2) (%)')),
                ('dyspnea', models.TextField(verbose_name='Одышка')),
                ('cough', models.TextField(verbose_name='Кашель')),
                ('sputum', models.TextField(verbose_name='Мокрота')),
                ('hemoglobin', models.TextField(verbose_name='Гемоглобин (г\\л)')),
                ('leukocytes', models.TextField(verbose_name='Лейкоциты (Клеток 10^9)')),
                ('lymphocytes', models.TextField(verbose_name='Лимфоциты (%)')),
                ('platelets', models.TextField(verbose_name='Тромбоциты (Клеток 10^9)')),
                ('ESR', models.TextField(verbose_name='СОЭ (Мм/час)')),
                ('cReactiveProtein', models.TextField(verbose_name='С-реактивный белок (г\\л)')),
                ('oxygenTension', models.TextField(verbose_name='Респираторный индекс')),
                ('pH', models.TextField(verbose_name='pH')),
                ('oxygenFraction', models.TextField(verbose_name='Фракция кислорода на вдохе (%)')),
                ('respirationRate', models.TextField(verbose_name='Частота дыханий (Мин^-1)')),
                ('respiratoryVolume', models.TextField(verbose_name='Дыхательный объем (мл)')),
                ('endExpiratoryPressure', models.TextField(verbose_name='Конечно-экспираторное давление (См.вод.ст.)')),
                ('ventilationMode', models.TextField(verbose_name='Режим ИВЛ')),
                ('status', models.TextField(verbose_name='Оценка состояния')),
                ('doctor', models.TextField(verbose_name='Врач')),
                ('phone', models.TextField(verbose_name='Контактный телефон')),
                ('eMail', models.TextField(verbose_name='e-mail')),
                ('daysUndersupervision', models.TextField(verbose_name='Количество суток под наблюдением в ДРКЦ')),
                ('enterDate', models.TextField(verbose_name='Дата поступления')),
                ('entryDate', models.TextField(verbose_name='Дата внесения')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Полное имя'),
        ),
    ]
